/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.27
 * Generated at: 2019-04-09 08:21:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.wini;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/tlds/paging.tld", Long.valueOf(1553348524000L));
    _jspx_dependants.put("jar:file:/C:/blockchain_dev/workspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/verifiablecredential/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.9.RELEASE.jar", Long.valueOf(1554797606526L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1554797617524L));
    _jspx_dependants.put("jar:file:/C:/blockchain_dev/workspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/verifiablecredential/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/blockchain_dev/workspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/verifiablecredential/WEB-INF/lib/spring-webmvc-4.3.9.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1496830342000L));
    _jspx_dependants.put("/WEB-INF/views/common/common.jsp", Long.valueOf(1553428321631L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /WEB-INF/views/common/common.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("today");
        // /WEB-INF/views/common/common.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(new java.util.Date());
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("     <title>블럭체인 자격확인 관리자</title>\r\n");
      out.write("     <meta charset=\"utf-8\">\r\n");
      out.write("     <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/bootstrap/css/bootstrap.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/common.css\">\r\n");
      out.write("     <script type=\"text/javascript\" src=\"/resources/js/jQuery-3.3.1.min.js\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"/resources/bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"/resources/js/common.js\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"/resources/js/jqt.util.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resources/js/jqt.validate.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resources/js/jqt.form.js\"></script>\r\n");
      out.write(" </head>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Wini</title>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div id=\"contents-area\" class=\"container-fluid wini-back\" style=\"width:1223px;\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-wini-mobile\" data-toggle=\"modal\" data-target=\"#exampleModalCenter\">모바일 신분증 연동</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal -->\r\n");
      out.write("        <div class=\"modal fade\" id=\"exampleModalCenter\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-dialog-centered modal-lg\" role=\"document\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header custom-modal-header\">\r\n");
      out.write("                        <h5 class=\"modal-title\" id=\"exampleModalCenterTitle\">모바일 신분증 연동</h5>\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                            <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <div class=\"container-fluid custom-container p-5\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <ul class=\"nav nav-tabs\">\r\n");
      out.write("                                        <li class=\"nav-item step1 active\">1.발급처 선택<i></i></li>\r\n");
      out.write("                                        <li class=\"nav-item step2\">2.신분증/자격증명 선택<i></i></li>\r\n");
      out.write("                                        <li class=\"nav-item step3\">3.연동 정보 선택<i></i></li>\r\n");
      out.write("                                        <li class=\"nav-item step4\">4.QR코드 생성<i></i></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"tab-content\">\r\n");
      out.write("                                        <div id=\"step1\" class=\"tab-pane fadein active\">\r\n");
      out.write("                                            <table class=\"table table-bordered table-in-modal\">\r\n");
      out.write("                                                <thead>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                        <th>번호</th>\r\n");
      out.write("                                                        <th>발급처 목록</th>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                </thead>\r\n");
      out.write("                                                <tbody>\r\n");
      out.write("                                                </tbody>\r\n");
      out.write("                                            </table>\r\n");
      out.write("                                            <div class=\"text-center\">\r\n");
      out.write("                                                <button type=\"button\" class=\"btn btn-previous\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("                                                <button type=\"button\" class=\"btn btn-next\" onclick=\"onStep2();\">다음</button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div id=\"step2\" class=\"tab-pane fade\">\r\n");
      out.write("                                            <table class=\"table table-bordered table-in-modal\">\r\n");
      out.write("                                                <thead>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                        <th></th>\r\n");
      out.write("                                                        <th>번호</th>\r\n");
      out.write("                                                        <th>신분자격증명목록</th>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                </thead>\r\n");
      out.write("                                                <tbody>\r\n");
      out.write("                                                </tbody>\r\n");
      out.write("                                            </table>\r\n");
      out.write("                                            <div class=\"text-center\">\r\n");
      out.write("                                                <button class=\"btn btn-previous\" data-toggle=\"tab\" href=\"#step1\" onclick=\"onStep1();\">이전</button>\r\n");
      out.write("                                                <button class=\"btn btn-next\"  data-toggle=\"tab\" href=\"#step3\" onclick=\"onStep3();\">다음</button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div id=\"step3\" class=\"tab-pane fade\">\r\n");
      out.write("                                            <table class=\"table table-bordered table-in-modal\">\r\n");
      out.write("                                                <thead>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                        <th>\r\n");
      out.write("                                                            <input type=\"checkbox\" id=\"step3AllCheck\" onclick=\"step3Check(this);\">\r\n");
      out.write("                                                        </th>\r\n");
      out.write("                                                        <th>번호</th>\r\n");
      out.write("                                                        <th>연동 정보 목록</th>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                </thead>\r\n");
      out.write("                                                <tbody>\r\n");
      out.write("                                                </tbody>\r\n");
      out.write("                                            </table>\r\n");
      out.write("                                            <div class=\"text-center\">\r\n");
      out.write("                                                <button class=\"btn btn-previous\" data-toggle=\"tab\" href=\"#step2\" onclick=\"disConnect();onStep2();\">이전</button>\r\n");
      out.write("                                                <button class=\"btn btn-next\" data-toggle=\"tab\" href=\"#step4\" onclick=\"onStep4();\">다음</button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div id=\"step4\" class=\"tab-pane fade\">\r\n");
      out.write("                                            <div class=\"container\">\r\n");
      out.write("                                                <div class=\"row justify-content-md-center\">\r\n");
      out.write("                                                    <div id=\"qr\" style=\"text-align: center;\">\r\n");
      out.write("                                                        <img src=\"/resources/images/QR/qr-code.png\">\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"col-12\">\r\n");
      out.write("                                                        <p class=\"text-center p-3\">QR코드를 고객님 촬영하시면 연동이 완료됩니다.</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-center\">\r\n");
      out.write("                                                <button class=\"btn btn-previous\" data-toggle=\"tab\" href=\"#step3\" onclick=\"onStep3();\">이전</button>\r\n");
      out.write("                                                <button type=\"button\" class=\"btn btn-previous\" data-dismiss=\"modal\" onclick=\"location.reload();\">닫기</button>\r\n");
      out.write("                                                <!-- <button class=\"btn btn-next\" data-toggle=\"tab\" href=\"#step5\" onclick=\"onStep5();\">다음</button>-->\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div id=\"step5\" class=\"tab-pane fade\">\r\n");
      out.write("                                            <div class=\"container\">\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                    <div class=\"col-12 text-center\">\r\n");
      out.write("                                                        <img src=\"d://photo//photo.png\" style=\"height:162px; border:3px solid #ddd;\" class=\"mt-5 mb-3\">\r\n");
      out.write("                                                        <h6 class=\"text-center p-3\" style=\"font-size:18px;\"><div id=\"korNm\" style=\"color: #007bff;\">김우리</div> 고객님의 모바일 신분증 인증정보가<br>연동되었습니다.</h6>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"col-12\">\r\n");
      out.write("                                                        <table class=\"table table-bordered table-in-modal-2\">\r\n");
      out.write("                                                            <tbody>\r\n");
      out.write("                                                                <tr>\r\n");
      out.write("                                                                    <th>한글이름</th>\r\n");
      out.write("                                                                    <td><div id=\"kornm2\">김우리</div></td>\r\n");
      out.write("                                                                </tr>\r\n");
      out.write("                                                                <tr>\r\n");
      out.write("                                                                    <th>주민등록번호</th>\r\n");
      out.write("                                                                    <td>900406-1742933</td>\r\n");
      out.write("                                                                </tr>\r\n");
      out.write("                                                                <tr>\r\n");
      out.write("                                                                    <th>주소</th>\r\n");
      out.write("                                                                    <td>서울시 중구 소공로 51</td>\r\n");
      out.write("                                                                </tr>\r\n");
      out.write("                                                                <tr>\r\n");
      out.write("                                                                    <th>발급일</th>\r\n");
      out.write("                                                                    <td>2018.01.02</td>\r\n");
      out.write("                                                                </tr>\r\n");
      out.write("                                                                <tr>\r\n");
      out.write("                                                                    <th>발급처</th>\r\n");
      out.write("                                                                    <td>서울특별시 중구구청장</td>\r\n");
      out.write("                                                                </tr>\r\n");
      out.write("                                                            </tbody>\r\n");
      out.write("                                                        </table>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-center\">\r\n");
      out.write("                                                <button type=\"button\" class=\"btn btn-previous\" data-dismiss=\"modal\" onclick=\"location.reload();\">닫기</button>\r\n");
      out.write("                                                <button type=\"button\" class=\"btn btn-start-counsel\" data-dismiss=\"modal\" onclick=\"location.reload();\">상담시작</button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <form id=\"commonCode\" name=\"commonCode\" action=\"\" method=\"POST\" onsubmit=\"return false;\" >\r\n");
      out.write("        \t<input type=\"hidden\" id=\"cd\" name=\"cd\" value=\"\" />\r\n");
      out.write("        \t<input type=\"hidden\" id=\"uppCd\" name=\"uppCd\" value=\"\" />\r\n");
      out.write("        \t<input type=\"hidden\" id=\"cdNm\" name=\"cdNm\" value=\"\" />\r\n");
      out.write("        \t<input type=\"hidden\" id=\"level\" name=\"level\" value=\"\" />\r\n");
      out.write("        \t<input type=\"hidden\" id=\"orderNo\" name=\"orderNo\" value=\"\" />\r\n");
      out.write("        \t<input type=\"hidden\" id=\"useFl\" name=\"useFl\" value=\"\" />\r\n");
      out.write("        \t<input type=\"hidden\" id=\"issuedPlaceCd\" name=\"issuedPlaceCd\" value=\"\" />\r\n");
      out.write("        \t<input type=\"hidden\" id=\"certiCd\" name=\"certiCd\" value=\"\" />\r\n");
      out.write("        \t<input type=\"hidden\" id=\"sid\" value=\"");
      out.print(request.getSession().getAttribute("sid") );
      out.write("\" />\r\n");
      out.write("        </form> \r\n");
      out.write("    </body>\r\n");
      out.write(" </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
